import Link from "next/link";

export const metadata = {
  title: "Terms of Service — DawaiSathi",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ background: "#0d1c24", color: "#f0f8ff" }}>
      {/* Header */}
      <header
        className="sticky top-0 z-40 px-6 py-4 flex items-center justify-between"
        style={{ background: "#0d1c24", borderBottom: "1px solid rgba(255,255,255,0.06)" }}
      >
        <Link href="/" className="font-semibold text-sm hover:opacity-80 transition-opacity">
          ← DawaiSathi
        </Link>
        <span className="text-xs" style={{ color: "#a8bec9" }}>Terms of Service</span>
      </header>

      {/* Content */}
      <main className="max-w-2xl mx-auto px-6 py-12">
        <h1 className="text-2xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm mb-8" style={{ color: "#a8bec9" }}>Last updated: March 2025</p>

        <div className="space-y-8 text-sm leading-relaxed" style={{ color: "#c8d8e4" }}>
          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "#f0f8ff" }}>1. Acceptance of Terms</h2>
            <p>By accessing or using DawaiSathi (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "#f0f8ff" }}>2. Service Description</h2>
            <p>DawaiSathi is an AI-powered medicine information tool that provides <strong style={{ color: "#f0f8ff" }}>educational explanations</strong> of medicines in Indian languages. The Service is provided <strong style={{ color: "#f0f8ff" }}>for informational purposes only</strong> and is not a medical service.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "#f0f8ff" }}>3. Not a Substitute for Medical Advice</h2>
            <p className="mb-3">The explanations generated by DawaiSathi are <strong style={{ color: "#fbe2a7" }}>not a substitute for professional medical advice, diagnosis, or treatment.</strong></p>
            <p><strong style={{ color: "#f0f8ff" }}>You must consult a licensed doctor, pharmacist, or other qualified healthcare provider</strong> before making any medical decisions, starting, stopping, or modifying any medication, or if you have questions about your health condition.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "#f0f8ff" }}>4. Limitation of Liability</h2>
            <p className="mb-3">DawaiSathi and its operators are <strong style={{ color: "#f0f8ff" }}>not liable for any health decisions made based on explanations provided by this Service.</strong></p>
            <p>AI-generated content may contain inaccuracies, outdated information, or errors. Always verify medicine information with a licensed professional. DawaiSathi shall not be held responsible for any adverse health outcomes resulting from reliance on information provided through the Service.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "#f0f8ff" }}>5. Payment Terms</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>AI-generated medicine explanations are free and unlimited for all users.</li>
              <li>Connecting with a certified pharmacist for a personal callback is a paid feature, priced at ₹50 per request.</li>
              <li><strong style={{ color: "#f0f8ff" }}>No refunds on completed services.</strong> Once a pharmacist callback has been fulfilled, the transaction is final and non-refundable.</li>
              <li>Payments are processed securely via Razorpay. We do not store payment card information.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "#f0f8ff" }}>6. User Obligations</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>You must be at least 18 years of age or have parental consent to use this Service.</li>
              <li>You agree not to misuse the Service, including submitting false information or attempting to circumvent usage limits.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "#f0f8ff" }}>7. Intellectual Property</h2>
            <p>All content, design, and code of DawaiSathi is the property of its operators. AI-generated explanations are provided for your personal, non-commercial use only.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "#f0f8ff" }}>8. Modifications</h2>
            <p>We reserve the right to modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "#f0f8ff" }}>9. Governing Law</h2>
            <p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in Bengaluru, Karnataka, India.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "#f0f8ff" }}>10. Contact</h2>
            <p>For questions about these Terms, contact: <a href="mailto:team@dawaisathi.in" style={{ color: "#fbe2a7" }}>team@dawaisathi.in</a></p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer
        className="px-6 py-6 text-center"
        style={{ borderTop: "1px solid rgba(255,255,255,0.06)" }}
      >
        <p className="text-xs space-x-4" style={{ color: "#4a6a7a" }}>
          <Link href="/privacy" className="hover:opacity-80 transition-opacity">Privacy</Link>
          <span>·</span>
          <Link href="/terms" className="hover:opacity-80 transition-opacity" style={{ color: "#fbe2a7" }}>Terms</Link>
          <span>·</span>
          <Link href="/disclaimer" className="hover:opacity-80 transition-opacity">Disclaimer</Link>
        </p>
      </footer>
    </div>
  );
}
